<?php
/**
 * The llms.txt "layer 2" own-namespace Markdown index — a permanent, always
 * available list of every published FAQ/KB/glossary item, meant to be linked
 * to from the site's root llms.txt (usually generated by an SEO plugin) or
 * discovered directly by a crawler (docs/DESIGN.md section 7.2, layer 2).
 *
 * @package SAAI\Knowledge
 */

namespace SAAI\Knowledge;

defined( 'ABSPATH' ) || exit;

/**
 * Serves `/{kb slug}/llms.txt` (e.g. `/kb/llms.txt`).
 */
final class Llms_Index {

	/**
	 * The query var this feature's rewrite rule maps to.
	 *
	 * @var string
	 */
	private const QUERY_VAR = 'saai_llms_index';

	/**
	 * Transient key the rendered index is cached under.
	 *
	 * @var string
	 */
	private const CACHE_KEY = 'saai_llms_index';

	/**
	 * How long the rendered index is cached for.
	 *
	 * @var int
	 */
	private const CACHE_TTL = HOUR_IN_SECONDS;

	/**
	 * Upper bound on how many items of one content type are listed. A cap
	 * (rather than posts_per_page => -1) keeps a very large KB from
	 * producing an unbounded response on every cache miss.
	 *
	 * @var int
	 */
	private const MAX_ITEMS_PER_TYPE = 1000;

	/**
	 * Hooks the rewrite rule, the request handler, and cache invalidation
	 * into WordPress.
	 *
	 * The rewrite rule itself is registered unconditionally (like
	 * Post_Types' CPT rewrite slugs) — only the actual serving in
	 * maybe_serve() is gated by the ai_readability_enabled setting. Gating
	 * the rule's existence on that setting too would require wiring a
	 * dedicated deferred-flush flag for it (Settings::maybe_flush_rewrite_rules()
	 * only covers the three slug fields), for no real benefit: a disabled
	 * feature whose URL is guessed simply falls through to whatever
	 * WordPress's own main query resolves an unrecognized `saai_llms_index`
	 * query var to (verified against a live wp-env instance: the front
	 * page, not a 404) — no worse than if the route had never been
	 * registered at all.
	 */
	public function register(): void {
		add_action( 'init', array( $this, 'add_rewrite_rule' ) );
		add_action( 'wp_loaded', array( $this, 'maybe_remove_canonical_redirect' ) );
		add_action( 'template_redirect', array( $this, 'maybe_serve' ) );

		add_action( 'save_post_saai_faq', array( $this, 'flush_cache' ) );
		add_action( 'save_post_saai_kb', array( $this, 'flush_cache' ) );
		add_action( 'save_post_saai_glossary', array( $this, 'flush_cache' ) );
		add_action( 'trashed_post', array( $this, 'flush_cache' ) );
		// wp_delete_post( $id, true ) (REST's force=true, `wp post delete
		// --force`, WP-CLI's default for CPTs without Trash support) skips
		// wp_trash_post() entirely, so trashed_post never fires — only
		// deleted_post does (Codex review; Autolinker::handle_post_deleted()
		// already needs the same second hook for the same reason).
		add_action( 'deleted_post', array( $this, 'flush_cache' ) );
		add_action( 'update_option_saai_knowledge_settings', array( $this, 'maybe_flush_cache_on_slug_change' ), 10, 2 );
	}

	/**
	 * Adds the `^{kb slug}/llms\.txt$` rewrite rule and registers its query
	 * var. 'top' priority is required: without it, the saai_kb post type's
	 * own (looser) `^{kb slug}/([^/]+)/?$` single-article rule would win
	 * first and try to resolve "llms.txt" as an article slug.
	 */
	public function add_rewrite_rule(): void {
		add_rewrite_rule( '^' . $this->kb_slug() . '/llms\.txt$', 'index.php?' . self::QUERY_VAR . '=1', 'top' );
		add_rewrite_tag( '%' . self::QUERY_VAR . '%', '([0-1]{1})' );
	}

	/**
	 * Removes core's redirect_canonical() for this one request. Without
	 * this, WordPress's own trailing-slash/canonicalization logic for
	 * pretty permalinks can redirect a request for a rewrite-rule-only
	 * endpoint like this one before it ever reaches maybe_serve() — the
	 * same fix Rank Math's own llms.txt module applies to its root
	 * `/llms.txt` route (verified against its source, see the Llms_Txt_Adapter
	 * class docblock for how that source was consulted).
	 *
	 * The wp_loaded action fires before request parsing, so the query var
	 * isn't available yet here; checking the raw request URI is what Rank
	 * Math's own equivalent does too.
	 *
	 * Matched against the request's *path* only (via wp_parse_url(),
	 * PHP_URL_PATH) — not the raw $_SERVER['REQUEST_URI'] — and anchored to
	 * the end of it. Two false-positive classes that a plain substring
	 * search against the full REQUEST_URI (query string included) would
	 * hit otherwise:
	 * - a real article at e.g. `/{kb slug}/llms.txt-guide/` (its path
	 *   starts with the exact same characters as ours) — the earlier
	 *   Codex-review fix for this specifically is why the pattern is
	 *   end-anchored rather than a bare strpos();
	 * - an unrelated request whose *query string* merely happens to
	 *   contain the same characters, e.g. `/search/?q=/kb/llms.txt`
	 *   (Copilot review) — fixed by matching only the path component.
	 *
	 * It stays a substring search within that path (not an anchored
	 * full-path match) so a subdirectory-install prefix still matches.
	 *
	 * remove_filter()'s $priority defaults to 10 when omitted — core
	 * registers redirect_canonical there, but if some other plugin/theme
	 * re-hooked it at a different priority, an unqualified remove_filter()
	 * call would silently fail to match it, leaving the redirect in place
	 * (Copilot review). has_filter() (which returns the actual registered
	 * priority, or false) removes that assumption.
	 */
	public function maybe_remove_canonical_redirect(): void {
		// Not sanitize_text_field(): its percent-encoded-octet stripping
		// (core's _sanitize_text_fields()) would delete every %XX byte from
		// a non-ASCII kb_slug() — e.g. sanitize_title( '日本語' ) stores as
		// literal "%e3%81%..." — breaking the match below for any request
		// whose path contains one. This value is only ever compared against
		// $pattern, never output, so wp_unslash() alone is correct (Codex
		// review; regression from an earlier unsanitized-input hardening
		// pass caught by review-loop).
		// phpcs:ignore WordPress.Security.ValidatedSanitizedInput.InputNotSanitized
		$request_uri = isset( $_SERVER['REQUEST_URI'] ) ? wp_unslash( (string) $_SERVER['REQUEST_URI'] ) : '';
		$path        = (string) wp_parse_url( $request_uri, PHP_URL_PATH );
		$pattern     = '#/' . preg_quote( $this->kb_slug(), '#' ) . '/llms\.txt/?$#';

		if ( 1 !== preg_match( $pattern, $path ) ) {
			return;
		}

		$priority = has_filter( 'template_redirect', 'redirect_canonical' );

		if ( false !== $priority ) {
			remove_filter( 'template_redirect', 'redirect_canonical', $priority );
		}
	}

	/**
	 * Serves the index and exits when the current request matched this
	 * feature's rewrite rule; otherwise a no-op.
	 */
	public function maybe_serve(): void {
		if ( ! $this->enabled() ) {
			return;
		}

		if ( '1' !== (string) get_query_var( self::QUERY_VAR ) ) {
			return;
		}

		header( 'Content-Type: text/markdown; charset=utf-8' );
		header( 'X-Content-Type-Options: nosniff' );
		// noindex (this listing page itself isn't meant to rank) but
		// deliberately not nofollow: this index's entire purpose is being a
		// discovery/link hub crawlers follow into the actual FAQ/KB/glossary
		// pages (docs/DESIGN.md section 7.2, layer 2) — nofollow would
		// defeat that (Codex review).
		header( 'X-Robots-Tag: noindex' );
		// phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- build_index_cached() builds a plain-text Markdown document (not HTML) for a text/markdown response; see build_index()'s docblock.
		echo $this->build_index_cached();
		exit;
	}

	/**
	 * Returns the cached rendered index, building and caching it on a miss.
	 *
	 * @return string
	 */
	public function build_index_cached(): string {
		$cached = get_transient( self::CACHE_KEY );

		if ( is_string( $cached ) ) {
			return $cached;
		}

		$index = $this->build_index();

		set_transient( self::CACHE_KEY, $index, self::CACHE_TTL );

		return $index;
	}

	/**
	 * Deletes the cached index. Hooked to save/trash of the three content
	 * post types; a stale cache otherwise only self-heals after CACHE_TTL.
	 */
	public function flush_cache(): void {
		delete_transient( self::CACHE_KEY );
	}

	/**
	 * Flushes the cached index when a saai_knowledge_settings save changes
	 * slug_kb, slug_faq, or slug_glossary. build_index_cached() embeds each
	 * item's get_permalink(), which changes as soon as Post_Types
	 * re-registers the affected post type with its new slug on the next
	 * `init` — without this, the cache would keep serving links to the old,
	 * now-404ing URLs for up to CACHE_TTL (Codex review). Same slug-change
	 * detection Settings::finalize_slugs() and Autolinker's dictionary
	 * generation bump already use.
	 *
	 * @param mixed $old_value Previous `saai_knowledge_settings` value.
	 * @param mixed $new_value New `saai_knowledge_settings` value.
	 */
	public function maybe_flush_cache_on_slug_change( $old_value, $new_value ): void {
		$old_value = is_array( $old_value ) ? $old_value : array();
		$new_value = is_array( $new_value ) ? $new_value : array();

		foreach ( array( 'slug_kb', 'slug_faq', 'slug_glossary' ) as $key ) {
			$old = $old_value[ $key ] ?? null;
			$new = $new_value[ $key ] ?? null;

			if ( $old !== $new ) {
				$this->flush_cache();
				return;
			}
		}
	}

	/**
	 * Builds the Markdown index: a heading per content type, each with a
	 * bullet list of `[Title](URL) ([Markdown](markdown URL))` links.
	 *
	 * @return string
	 */
	public function build_index(): string {
		$items = apply_filters( 'saai_llms_index_items', $this->collect_items() );
		$items = is_array( $items ) ? $items : array();

		$grouped = array();

		foreach ( $items as $item ) {
			if ( ! is_array( $item ) || ! self::is_valid_index_item( $item ) ) {
				continue;
			}

			$grouped[ $item['type'] ][] = $item;
		}

		// The site name is as editable/arbitrary as a post title — escape it
		// the same way, or a name containing '[', '*', '`', etc. could break
		// or be misread as formatting in this H1 (Copilot review).
		$site_name = html_entity_decode( wp_strip_all_tags( get_bloginfo( 'name' ) ), ENT_QUOTES | ENT_SUBSTITUTE | ENT_HTML5, 'UTF-8' );
		$site_name = Markdown_Converter::escape_text( str_replace( array( "\r", "\n" ), ' ', $site_name ) );
		$lines     = array( '# ' . $site_name . ' — Knowledge Index', '' );
		$labels    = $this->type_labels();

		foreach ( $grouped as $type => $type_items ) {
			$lines[] = '## ' . ( $labels[ $type ] ?? ucfirst( $type ) );

			foreach ( $type_items as $item ) {
				// An unescaped ']' or '[' in the title would close the link
				// label early (or open a bogus nested one), corrupting the
				// URL that follows or getting misread as a separate link
				// (Codex review) — titles are arbitrary display strings, so
				// this can't just be assumed away. Markdown_Converter::escape_text()
				// is the same escaping Markdown_Output uses for its own
				// title-as-heading case.
				$title = Markdown_Converter::escape_text( str_replace( array( "\r", "\n" ), ' ', (string) $item['title'] ) );

				// url/markdown_url come from a saai_llms_index_items
				// callback — a public filter, so a value containing an
				// unbalanced ')' (or a literal '<'/'>') can't be assumed
				// away either; wrap both the same way Markdown_Converter
				// wraps an href/src (Copilot review).
				$url          = Markdown_Converter::markdown_link_destination( $item['url'] );
				$markdown_url = Markdown_Converter::markdown_link_destination( $item['markdown_url'] );
				$lines[]      = '- [' . $title . '](' . $url . ') ([Markdown](' . $markdown_url . '))';
			}

			$lines[] = '';
		}

		return trim( implode( "\n", $lines ) ) . "\n";
	}

	/**
	 * Whether an item from `saai_llms_index_items` actually satisfies the
	 * documented item shape (docs/DESIGN-HOOKS-API.md section 3.4): all
	 * four keys present *and* non-empty strings. `saai_llms_index_items` is
	 * a public filter (Copilot review), so an isset()-only check (allowing
	 * e.g. an array or an int through as `url`) risks a PHP "Array to
	 * string conversion" notice or a broken `[]()` link once concatenated
	 * into the output — a third-party callback can't be trusted to honor
	 * the contract just because the keys exist.
	 *
	 * @param array<string, mixed> $item Candidate item.
	 * @return bool
	 */
	private static function is_valid_index_item( array $item ): bool {
		foreach ( array( 'type', 'title', 'url', 'markdown_url' ) as $key ) {
			if ( ! isset( $item[ $key ] ) || ! is_string( $item[ $key ] ) || '' === $item[ $key ] ) {
				return false;
			}
		}

		return true;
	}

	/**
	 * Queries every published item of each content type and shapes it into
	 * the `saai_llms_index_items` item form (docs/DESIGN-HOOKS-API.md
	 * section 3.4): `[ 'type', 'title', 'url', 'markdown_url' ]`.
	 *
	 * @return array<int, array{type: string, title: string, url: string, markdown_url: string}>
	 */
	private function collect_items(): array {
		$items = array();

		foreach ( $this->post_types() as $type_key => $post_type ) {
			$query = new \WP_Query(
				array(
					'post_type'           => $post_type,
					'post_status'         => 'publish',
					'has_password'        => false,
					'posts_per_page'      => self::MAX_ITEMS_PER_TYPE,
					'orderby'             => 'title',
					'order'               => 'ASC',
					'no_found_rows'       => true,
					'ignore_sticky_posts' => true,
				)
			);

			foreach ( $query->posts as $post ) {
				if ( ! $post instanceof \WP_Post ) {
					continue;
				}

				$url = get_permalink( $post );

				if ( ! is_string( $url ) || '' === $url ) {
					continue;
				}

				$items[] = array(
					'type'         => $type_key,
					'title'        => html_entity_decode( wp_strip_all_tags( get_the_title( $post ) ), ENT_QUOTES | ENT_SUBSTITUTE | ENT_HTML5, 'UTF-8' ),
					'url'          => $url,
					'markdown_url' => add_query_arg( 'format', 'markdown', $url ),
				);
			}
		}

		return $items;
	}

	/**
	 * The three content types this index always covers (unlike Search's
	 * post_types(), this is not saai_search_post_types-filterable — the
	 * llms.txt index is scoped to FAQ/KB/glossary by design, see
	 * docs/DESIGN.md section 7.2).
	 *
	 * @return array<string, string> Type key => post type.
	 */
	private function post_types(): array {
		return array(
			'faq'      => 'saai_faq',
			'kb'       => 'saai_kb',
			'glossary' => 'saai_glossary',
		);
	}

	/**
	 * Display labels for each type key, used as the Markdown section
	 * headings.
	 *
	 * @return array<string, string>
	 */
	private function type_labels(): array {
		return array(
			'faq'      => __( 'FAQ', 'saai-knowledge' ),
			'kb'       => __( 'Knowledge Base', 'saai-knowledge' ),
			'glossary' => __( 'Glossary', 'saai-knowledge' ),
		);
	}

	/**
	 * Reads the saai_kb rewrite slug the same way Post_Types::slug() does.
	 *
	 * @return string
	 */
	private function kb_slug(): string {
		$settings = get_option( 'saai_knowledge_settings' );

		if ( is_array( $settings ) && isset( $settings['slug_kb'] ) && is_string( $settings['slug_kb'] ) && '' !== $settings['slug_kb'] ) {
			return $settings['slug_kb'];
		}

		return 'kb';
	}

	/**
	 * Whether the AI-readability feature (Markdown output + llms.txt) is
	 * enabled. Same defensive get_option() read pattern as
	 * Breadcrumbs::structured_data_enabled().
	 *
	 * @return bool
	 */
	private function enabled(): bool {
		$settings = get_option( 'saai_knowledge_settings' );

		if ( ! is_array( $settings ) || ! array_key_exists( 'ai_readability_enabled', $settings ) ) {
			return true;
		}

		return (bool) $settings['ai_readability_enabled'];
	}
}
