name: JS Quality

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint-js:
    name: Lint JS
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-node@v5
        with:
          node-version: '24'
          cache: 'npm'

      - run: npm ci

      - run: npm run lint:js

  lint-css:
    name: Lint CSS
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-node@v5
        with:
          node-version: '24'
          cache: 'npm'

      - run: npm ci

      - run: npm run lint:css

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-node@v5
        with:
          node-version: '24'
          cache: 'npm'

      - run: npm ci

      - run: npm run build
